# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show_app', '0002_auto_20190724_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
